import { Geist, Geist_Mono, Lexend_Giga } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReelContextProvider from "@/Context/ReelContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const lexendgiga = Lexend_Giga({
  variable: "--font-lexend-giga",
  subsets: ["latin"],
});

export const metadata = {
  title: "Riko - A reel generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${lexendgiga.variable} ${geistMono.variable}  antialiased`}
      >
          <ReelContextProvider>
        {children}
        </ReelContextProvider>
         <Toaster/>
      </body>
    </html>
  );
}
